### ISSUE TITLE
Property 'userData' not valid for 'SoftLayer_Virtual_Guest'. (XMLRPC::FaultException)

### ISSUE THREAD

**Issue by vincenthuynh** [audiolize/vagrant-softlayer#62]
Hello,

We began encountering the following error on Jun 29th at ~4:30pm EST when trying to provision a device and it continues to affect us. Is anyone else encountering this error?

```
09:03:39 Bringing machine 'db01' up with 'softlayer' provider...
09:03:39 ==> db01: Creating a new SoftLayer instance...
09:03:54 ==> db01: Waiting for instance provisioning. This may take a few minutes...
09:03:54 /opt/vagrant/embedded/lib/ruby/2.0.0/xmlrpc/client.rb:266:in `call': Property 'userData' not valid for 'SoftLayer_Virtual_Guest'. (XMLRPC::FaultException)
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/softlayer_api-3.0.2/lib/softlayer/Service.rb:267:in `call_softlayer_api_with_params'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/softlayer_api-3.0.2/lib/softlayer/APIParameterFilter.rb:194:in `method_missing'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/softlayer_api-3.0.2/lib/softlayer/VirtualServer.rb:174:in `server_with_id'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-softlayer-0.4.0/lib/vagrant-softlayer/action/wait_for_provision.rb:20:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-softlayer-0.4.0/lib/vagrant-softlayer/action/create_instance.rb:23:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/action/update_all.rb:33:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:80:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-softlayer-0.4.0/lib/vagrant-softlayer/action/setup_softlayer.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-softlayer-0.4.0/lib/vagrant-softlayer/action/setup_softlayer.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
09:03:54    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

And when we try to destroy the failed instance:

```
09:04:00 ==> db01: Destroying the SoftLayer instance...
09:04:00 Vagrant returned an exception while calling the SoftLayer API.
09:04:00 
09:04:00 Exception class: XMLRPC::FaultException
09:04:00 Exception message: A billing item is required to process a cancellation.
```

If it matters, we are able to manually order a device through the SL Control Portal.
@underscorephil, @SLsthompson

**Comment by vincenthuynh** [comment]
June 30th ~11:10am EST: The issue seems to have been fixed. 

Any insight whether it was resolved in the backend?

**Comment by underscorephil** [comment]
Howdy!

This was on the API side and should be resolved.

**Comment by vincenthuynh** [comment]
Yup, thanks for the info!

For posterity, this was the reply from SL support:

> Yes, that is correct. There was a change which caused this problem and the fix for it was released this >morning. The error you should have gotten should have been something like this:
> 
> SoftLayerAPIError(SoftLayer_Exception_WebService_ObjectMask): Property 'userData' not valid for >'SoftLayer_Virtual_Guest'.
