### ISSUE TITLE
Error Downloading Box File

### ISSUE THREAD

**Issue by poflynn** [audiolize/vagrant-softlayer#64]
I have an easy workaround for this but thought I'd log this nonetheless. On a new machine my vagrant up fails with this error:

```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
```

However, when I do a 'vagrant box add SoftLayer http://<servername>/nexus/content/repositories/veevaEnv/softlayer/box/1.0/box-1.0.box' it downloads it fine and then afterwards my 'vagrant up's are all successful.

Tiny Vagrantfile excerpt and debug log below. Note the proper URLs have been redacted.

Thanks,

Paul

```
config.vm.provider :softlayer do |provider, override|
        override.vm.box = 'SoftLayer'  
        provider.box_url = 'http://<servername>/nexus/content/repositories/veevaEnv/softlayer/box/1.0/box-1.0.box'    
```

```
 INFO interface: info: Bringing machine 'default' up with 'softlayer' provider...
Bringing machine 'default' up with 'softlayer' provider...
 INFO machine: Calling action: read_state on provider SoftLayer (new VM)
DEBUG environment: Attempting to acquire process-lock: machine-action-9d7ad00dab36eb83a7cf0b97d0e6d4d3
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-9d7ad00dab36eb83a7cf0b97d0e6d4d3
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_state #<Vagrant::Action::Builder:0x0000010219afc0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000001021bb400>
 INFO warden: Calling IN action: #<VagrantPlugins::SoftLayer::Action::SetupSoftLayer:0x000001021bb338>
 INFO connect_softlayer: Creating the SoftLayer service objects...
 INFO warden: Calling IN action: #<VagrantPlugins::SoftLayer::Action::ReadState:0x00000102242400>
 INFO warden: Calling OUT action: #<VagrantPlugins::SoftLayer::Action::ReadState:0x00000102242400>
 INFO warden: Calling OUT action: #<VagrantPlugins::SoftLayer::Action::SetupSoftLayer:0x000001021bb338>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x000001021bb400>
 INFO environment: Released process lock: machine-action-9d7ad00dab36eb83a7cf0b97d0e6d4d3
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because only executing one action
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x000001012617c0> up {:destroy_on_error=>true, :parallel=>true, :provision_ignore_sentinel=>true, :provision_types=>nil, :provider=>"softlayer", :provision_enabled=>false}
 INFO machine: Calling action: up on provider SoftLayer (new VM)
DEBUG environment: Attempting to acquire process-lock: machine-action-9d7ad00dab36eb83a7cf0b97d0e6d4d3
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-9d7ad00dab36eb83a7cf0b97d0e6d4d3
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000101258968>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleBox:0x000001009728a8>
 INFO interface: output: Box 'SoftLayer' could not be found. Attempting to find and install...
 INFO interface: output: ==> default: Box 'SoftLayer' could not be found. Attempting to find and install...
==> default: Box 'SoftLayer' could not be found. Attempting to find and install...
 INFO interface: detail: Box Provider: softlayer
 INFO interface: detail:     default: Box Provider: softlayer
    default: Box Provider: softlayer
 INFO interface: detail: Box Version: >= 0
 INFO interface: detail:     default: Box Version: >= 0
    default: Box Version: >= 0
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000100a288d8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BoxAdd:0x00000101231660>
 INFO environment: Running hook: authenticate_box_url
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x000001022d0868>
 INFO warden: Calling IN action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x00000101516fd8>
DEBUG client: No authentication token in environment or /Users/pauloflynn/.vagrant.d/data/vagrant_login_token
 INFO warden: Calling OUT action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x00000101516fd8>
 INFO box_add: Downloading box: SoftLayer => /Users/pauloflynn/.vagrant.d/tmp/boxa2e79a5739df26ff763b7313a27213d20548235d
 INFO box_add: URL is a file or protocol not found and assuming file.
 INFO interface: output: Box file was not detected as metadata. Adding it directly...
 INFO interface: output: ==> default: Box file was not detected as metadata. Adding it directly...
==> default: Box file was not detected as metadata. Adding it directly...
 INFO interface: output: Adding box 'SoftLayer' (v0) for provider: softlayer
 INFO interface: output: ==> default: Adding box 'SoftLayer' (v0) for provider: softlayer
==> default: Adding box 'SoftLayer' (v0) for provider: softlayer
 INFO box_collection: Box not found: SoftLayer (softlayer)
 INFO box_add: Downloading box: SoftLayer => /Users/pauloflynn/.vagrant.d/tmp/boxa2e79a5739df26ff763b7313a27213d20548235d
 INFO box_add: URL is a file or protocol not found and assuming file.
 INFO interface: detail: Downloading: SoftLayer
 INFO interface: detail:     default: Downloading: SoftLayer
    default: Downloading: SoftLayer
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: file:/Users/pauloflynn/workspace/vagrant2/SoftLayer
 INFO downloader:   -- Destination: /Users/pauloflynn/.vagrant.d/tmp/boxa2e79a5739df26ff763b7313a27213d20548235d
 INFO subprocess: Starting process: ["/opt/vagrant/embedded/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.7.4", "--continue-at", "-", "--output", "/Users/pauloflynn/.vagrant.d/tmp/boxa2e79a5739df26ff763b7313a27213d20548235d", "file:/Users/pauloflynn/workspace/vagrant2/SoftLayer"]
 INFO subprocess: Command in the installer. Specifying DYLD_LIBRARY_PATH...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: curl: (37) Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 37
 WARN downloader: Downloader exit code: 37

DEBUG box_add: Deleting temporary box: 
ERROR warden: Error occurred: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-9d7ad00dab36eb83a7cf0b97d0e6d4d3
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000001023c8860>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::DownloaderError: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer>
ERROR vagrant: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/downloader.rb:201:in `execute_curl'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/downloader.rb:134:in `download!'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:443:in `download'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:321:in `block in box_add'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:313:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:313:in `box_add'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:132:in `add_direct'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:106:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer
 INFO interface: Machine: error-exit ["Vagrant::Errors::DownloaderError", "An error occurred while downloading the remote file. The error\nmessage, if any, is reproduced below. Please fix this error and try\nagain.\n\nCouldn't open file /Users/pauloflynn/workspace/vagrant2/SoftLayer"]
```

**Comment by ju2wheels** [comment]
This should be opened upstream as its part of core vagrant functionality.
